## Rest API and HTTP

We'll work with rest api and http get and send request methos here.
We'll import requests libraray and have a url as shown

In [20]:
import requests
url='http://www.google.com'
r=requests.get(url)
#print(r.text)

#its memeber functions to get more details of r are
r.status_code
r.request.headers
r.request.body
r.headers
r.encoding
r.text[0:10]

'<!doctype '

## working witth randomuser API
RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum

In [21]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5067 sha256=86d2e8ea1c5a0b7adbe18ec514192eac4479d49374171045f0abb6bde3297f8b
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\41\6f\23\878c103a235dc2d4e85a3965c124aae8a28470c541b81aa2ba
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [24]:
from randomuser import RandomUser
import pandas as pd

In [33]:
r= RandomUser()
r
#a list of 10 users
somelist=r.generate_users(10)
somelist
#to get required details of a users
name=r.get_full_name()
name


#or to get full name of 10 users from the somelist we can
for user in somelist:
    print(user.get_full_name())
    
    
    
#similarly we can also fetch their gmail ids
for user in somelist:
    print(user.get_email())
    
    
    
#similarly we can also fetch their pictures
for user in somelist:
    print(user.get_picture())

Mirco Perrin
Elsie Steeves
Emilia Hokkanen
Mikkel Sørensen
Dimitrios Schaar
Floyd Porter
Susanne Johnston
Maja Kristensen
Natalia Gutierrez
Ethan Lee
mirco.perrin@example.com
elsie.steeves@example.com
emilia.hokkanen@example.com
mikkel.sorensen@example.com
dimitrios.schaar@example.com
floyd.porter@example.com
susanne.johnston@example.com
maja.kristensen@example.com
natalia.gutierrez@example.com
ethan.lee@example.com
https://randomuser.me/api/portraits/men/42.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/women/47.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/men/38.jpg
https://randomuser.me/api/portraits/men/27.jpg
https://randomuser.me/api/portraits/women/79.jpg
https://randomuser.me/api/portraits/women/21.jpg
https://randomuser.me/api/portraits/women/70.jpg
https://randomuser.me/api/portraits/men/30.jpg

NOw this helps in testing and other purposes by testers and developers if we add additional info and create a dummy databse of users.

In [39]:
def get_users():
    user=[]
    for sampleuser in RandomUser.generate_users(25):
        user.append({"Name": sampleuser.get_full_name(), 
                          "Gender": sampleuser.get_gender(),
                           "City": sampleuser.get_city(),
                           "State":sampleuser.get_state(),
                           "DOB":sampleuser.get_dob()})
    return pd.DataFrame(user)

ourdataframe=get_users()
ourdataframe

,Name,Gender,City,State,DOB
0,Miguel Hall,male,Perth,Western Australia,1966-09-24T11:58:43.444Z
1,Marten Hornig,male,Werne,Sachsen-Anhalt,1953-03-26T00:07:37.695Z
2,Gabrielle Addy,female,Chelsea,Saskatchewan,1975-02-28T16:27:06.038Z
3,Justine Barnaby,female,Aylmer,Manitoba,1966-08-30T01:06:14.824Z
4,Silas Sørensen,male,Støvring,Midtjylland,1952-03-03T21:50:14.047Z
5,Olivier Denys,male,Brockton,Saskatchewan,1969-07-07T12:01:29.402Z
6,Same Gardner,male,Warrnambool,Australian Capital Territory,1991-06-22T01:31:22.768Z
7,Micaela Ferreira,female,Sete Lagoas,Rio de Janeiro,1963-01-16T17:54:38.962Z
8,Grace Robertson,female,Brighton and Hove,West Sussex,1992-02-05T17:32:09.538Z
9,Lily Mitchelle,female,Cobh,South Dublin,1997-09-10T18:40:29.125Z
10,Adele Heiß,female,Gebesee,Rheinland-Pfalz,1968-04-16T20:06:25.920Z
11,Carmen Dupuis,female,St. Ursen,Aargau,1956-09-21T07:12:22.092Z
12,Daniel Macdonald,male,Selkirk,New Brunswick,1948-01-22T19:32:55.134Z
13,Judith Murphy,female,Brisbane,Western Australia,1978-03-23T10:40:39.689Z
14,Allan West,male,Roanoke,Maine,1987-11-29T06:53:06.126Z
15,Nicola Andre,male,La Tène,Zug,1977-01-26T10:38:47.953Z
16,پرهام علیزاده,male,گرگان,کرمان,1955-01-25T15:01:07.168Z
17,Avery Scott,female,Edinburgh,Lancashire,1978-12-07T17:34:15.456Z
18,Nathan Roy,male,Beaumont,Northwest Territories,1981-03-04T13:19:28.607Z
19,Marshall Elliott,male,Launceston,Western Australia,1983-10-24T09:45:38.419Z
20,Julian Smith,male,Mackay,Northern Territory,1945-07-28T02:27:21.037Z
21,Linnea Nevala,female,Veteli,Southern Ostrobothnia,1967-08-31T16:01:04.015Z
22,Amanda Burton,female,Wicklow,Dún Laoghaire–Rathdown,1980-01-06T12:51:51.542Z
23,Ayşe Nebioğlu,female,Bartın,Muğla,1953-12-08T09:38:43.815Z
24,Xavier Ennis,male,Cumberland,Québec,1956-10-28T16:01:57.520Z